name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 04
      id: test-04
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 04
        setup-command: ''
        command: go test ./ejercicios/ej04/... -run "^TestCasoBase$"
        timeout: 10
        max-score: 10
    - name: Test 02
      id: test-02
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 02
        setup-command: ''
        command: go test ./ejercicios/ej02/... -run "^TestCasoBase$"
        timeout: 10
        max-score: 10
    - name: Test 03
      id: test-03
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 03
        setup-command: ''
        command: go test ./ejercicios/ej03/... -run "^TestCasoBase$"
        timeout: 10
        max-score: 10
    - name: Test 04
      id: test-04
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 04
        setup-command: ''
        command: go test ./ejercicios/ej04/... -run "^TestCasoBase$"
        timeout: 10
        max-score: 10
    - name: 'Test 05 '
      id: test-05
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Test 05 '
        setup-command: ''
        command: go test ./ejercicios/ej05/... -run "^(TestEjemplo01|TestEjemplo02|TestEjemplo03)$"
        timeout: 10
        max-score: 30
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-04_RESULTS: "${{steps.test-04.outputs.result}}"
        TEST-02_RESULTS: "${{steps.test-02.outputs.result}}"
        TEST-03_RESULTS: "${{steps.test-03.outputs.result}}"
        TEST-05_RESULTS: "${{steps.test-05.outputs.result}}"
      with:
        runners: test-04,test-02,test-03,test-04,test-05
